// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductApi.Data;

#nullable disable

namespace ProductApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250519194517_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("ProductApi.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Gaming laptop",
                            ImageUrl = "",
                            Name = "Laptop",
                            Price = 1200m,
                            Stock = 10
                        },
                        new
                        {
                            ID = 2,
                            Description = "",
                            ImageUrl = "www.alza.cz",
                            Name = "Keyboard",
                            Price = 80m,
                            Stock = 0
                        },
                        new
                        {
                            ID = 3,
                            Description = "Wireless mouse",
                            ImageUrl = "www.alza.cz",
                            Name = "Mouse",
                            Price = 50m,
                            Stock = 15
                        },
                        new
                        {
                            ID = 4,
                            Description = "Wireless mouse",
                            ImageUrl = "www.alza.cz",
                            Name = "Smartphone",
                            Price = 850m,
                            Stock = 4
                        },
                        new
                        {
                            ID = 5,
                            Description = "Nice headphones",
                            ImageUrl = "",
                            Name = "Headphones",
                            Price = 90m,
                            Stock = 99
                        },
                        new
                        {
                            ID = 6,
                            Description = "Lego Technic 42207 Auto Ferrari SF-24 F1",
                            ImageUrl = "https://image.alza.cz/products/LO42207/LO42207.jpg?width=1400&height=1400",
                            Name = "Lego",
                            Price = 199.9m,
                            Stock = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
